#### Fix ssh access via keys if hosts are recreated.
#su - ansible -c "ssh-keygen -b 2048 -t rsa -f /home/ansible/.ssh/id_rsa -q -P \"\""
su - ansible -c "ssh-keyscan  ansible1.example.com 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  ansible2.example.com 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  ansible3.example.com 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  ansible4.example.com 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  ansible1 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  ansible2 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  ansible3 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  ansible4 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  control 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  control.example.com 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  192.168.4.200 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  192.168.4.201 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  192.168.4.202 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  192.168.4.203 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "ssh-keyscan  192.168.4.204 2>/dev/null >> /home/ansible/.ssh/known_hosts"
su - ansible -c "echo 'ansible' | sshpass ssh-copy-id -f -i /home/ansible/.ssh/id_rsa.pub -o StrictHostKeyChecking=no ansible@ansible1.example.com"
su - ansible -c "echo 'ansible' | sshpass ssh-copy-id -f -i /home/ansible/.ssh/id_rsa.pub -o StrictHostKeyChecking=no ansible@ansible2.example.com"
su - ansible -c "echo 'ansible' | sshpass ssh-copy-id -f -i /home/ansible/.ssh/id_rsa.pub -o StrictHostKeyChecking=no ansible@ansible3.example.com"
su - ansible -c "echo 'ansible' | sshpass ssh-copy-id -f -i /home/ansible/.ssh/id_rsa.pub -o StrictHostKeyChecking=no ansible@ansible4.example.com"
su - ansible -c "echo 'ansible' | sshpass ssh-copy-id -f -i /home/ansible/.ssh/id_rsa.pub -o StrictHostKeyChecking=no ansible@control.example.com"

